export const ACTIVITIES = [
  { text: "Take a 10-minute walk" },
  { text: "Practice coding for 15 minutes" },
  { text: "Read one chapter of a book" },
  { text: "Stretch for 5 minutes" },
  { text: "Meditate for 2 minutes" },
  { text: "Clean your desk" },
  { text: "Review your notes" },
  { text: "Drink a glass of water" },
  { text: "Do 20 squats" },
  { text: "Write down 3 things you're grateful for" },

  { text: "Organize one folder on your computer" },
  { text: "Practice a breathing exercise for 1 minute" },
  { text: "Wipe your phone screen" },
  { text: "Do 10 push-ups" },
  { text: "Review yesterday’s tasks" },
  { text: "Write down one goal for today" },
  { text: "Reply to one important message or email" },
  { text: "Stand up and stretch your back" },
  { text: "Practice typing for 5 minutes" },
  { text: "Visualize a positive outcome for something you’re worried about" },

  { text: "Refill your water bottle" },
  { text: "Do a quick clean-up of your room" },
  { text: "Walk around your home for 2 minutes" },
  { text: "Listen to one motivational song" },
  { text: "Journal for 3 minutes" },
  { text: "Review your to-do list" },
  { text: "Unsubscribe from one junk email list" },
  { text: "Delete 5 unnecessary photos or files" },
  { text: "Organize your backpack or workspace" },
  { text: "Take 5 slow deep breaths" },

  { text: "Do calf raises for 30 seconds" },
  { text: "Check your posture and fix it" },
  { text: "Look away from your screen for 20 seconds" },
  { text: "Do a light neck stretch" },
  { text: "Plan one thing to do tomorrow" },
  { text: "Read a short article" },
  { text: "Write down one habit you want to improve" },
  { text: "Stand up and move for 30 seconds" },
  { text: "Do 10 jumping jacks" },
  { text: "Watch a TV show" }

];